# This is a basic workflow to help you get started with Actions

name: USA - Scrape latest data

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Fetch latest data
        run: |-
          mkdir -p $GITHUB_WORKSPACE/data/usa
          curl -s "https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/votes-remaining-page/national/president.json" | jq . > $GITHUB_WORKSPACE/data/usa/results.json

      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
          
      - name: Setup python 
        uses: actions/setup-python@v3
        with: 
          python-version: "3.11"
